class AppImage {
  AppImage();

  String onboarding1 = "assets/image/onboarding1.png";
  String onboarding2 = "assets/image/onboarding2.png";
  String onboarding3 = "assets/image/onboarding3.png";
  String login_img = "assets/image/login_img.jpg";
  String key_img = "assets/image/key_img.png";
  String vehicle = "assets/image/vehicle.png";
  String car_profile = "assets/image/car_profile.png";
  String while_img = "assets/image/while_img.png";
  String wedding_img = "assets/image/wedding_img.png";
  String white_mercedes = "assets/image/white_mercedes.png";
  String white_sports_car = "assets/image/white_sports_car.png";
  String accountcar = "assets/image/accountcar.png";
  String coupon = "assets/image/coupon.png";
  String girlprofile = "assets/image/girlprofile.png";
  String car_stand = "assets/image/car_stand.png";
  String innova = "assets/image/innova.png";
  String addcard = "assets/image/addcard.png";
  String logout = "assets/image/logout.png";
  String bmw = "assets/image/bmw.png";
  String delete = "assets/image/delete.png";
  String deletedialog = "assets/image/deletedialog.png";
  String lambo = "assets/image/lambo.png";
  String Successfully = "assets/image/Successfully.png";
  String addquestion = "assets/image/addquestion.png";
}

class SvgImage {
  SvgImage();
  String splash = "assets/svg/splash.svg";
  String home = "assets/svg/home_icon.svg";
  String spendthreshold = "assets/svg/spendthreshold.svg";
  String cash = "assets/svg/cash.svg";
  String share = "assets/svg/share.svg";
  String offer = "assets/svg/offer.svg";
  String attachfile = "assets/svg/attachfile.svg";
  String right = "assets/svg/right.svg";
  String paymenticon = "assets/svg/paymenticon.svg";
  String visa = "assets/svg/visa.svg";
  String upi = "assets/svg/upi.svg";
  String expires = "assets/svg/expires.svg";
  String wrong = "assets/svg/wrong.svg";
  String addcard = "assets/svg/card-add.svg";
  String add = "assets/svg/add.svg";
  String logout = "assets/svg/logout.svg";
  String profile = "assets/svg/profile.svg";
  String notification = "assets/svg/notification.svg";
  String booking = "assets/svg/booking.svg";
  String paymentmethod = "assets/svg/paymentmethod.svg";
  String privacy = "assets/svg/privacy.svg";
  String terms = "assets/svg/terms.svg";
  String transaction = "assets/svg/transaction.svg";
  String coupons = "assets/svg/coupons.svg";
  String black = "assets/svg/black.svg";
  String number = "assets/svg/number.svg";
  String services = "assets/svg/services.svg";
  String whatsapp = "assets/svg/whatsapp.svg";
  String website = "assets/svg/website.svg";
  String delete = "assets/svg/delete.svg";
  String language = "assets/svg/language.svg";
  String faq = "assets/svg/faq.svg";
  String help = "assets/svg/help.svg";
  String grey = "assets/svg/grey.svg";
  String booking_car = "assets/svg/booking_car.svg";
  String vehicles_img = "assets/svg/vehicles_img.svg";
  String setting_img = "assets/svg/setting_img.svg";
  String seat = "assets/svg/seat.svg";
  String gear = "assets/svg/gear.svg";
  String petrol = "assets/svg/petrol.svg";
  String edit = "assets/svg/edit.svg";
  String payment = "assets/svg/payment.svg";
  String download_icon = "assets/svg/download.svg";
  String playbtn = "assets/svg/playbtn.svg";
  String download_icon_2 = "assets/svg/download_icon.svg";
  String camera = "assets/svg/camera.svg";
  String gallery = "assets/svg/gallery.svg";
}
